### ISSUE TITLE
Bug: Sensitive rotation div 2

### ISSUE THREAD

**Issue by r57zone** [terminal29/OSVR-Opentrack#1]
Hello, I found [one bug](https://github.com/infinitellamas/OSVR-Opentrack/blob/master/inf_osvr_opentrack.cpp#L153). Could you please fix it?

Required angle 180 instead of 360, to work with OpenTrack, i [checked & tested](https://github.com/r57zone/OpenVR-OpenTrack/blob/master/OpenVR/samples/driver_sample/driver_sample.cpp#L410).

And maybe [add](https://github.com/infinitellamas/OSVR-Opentrack/blob/master/inf_osvr_opentrack.cpp#L89) none blocking to socket?

> u_long nonblocking_enabled = TRUE;
> ioctlsocket(socketS, FIONBIO, &nonblocking_enabled);

Thanks.

**Comment by terminal29** [comment]
Ah yes my bad, i'll fix the conversion up and recompile in a bit.
What would adding non-blocking achieve?

**Comment by r57zone** [comment]
Well, or until you add a non blocking socket. I'm still testing.

**Comment by r57zone** [comment]
Thanks.
